sudo: required

services:
  - docker

before_install:
  - docker build -t amuljadhav222/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true amuljadhav222/docker-react npm run test -- --coverage